### ISSUE TITLE
Master Checklist

### ISSUE THREAD

**Issue by alexottoboni** [bbeck13/RhythmRunner#180]
## Main Features
- [x] Camera that changes (high pref)
- [x] Animated Character and platforms (high performance/arcade?)
- [x] Collision detection and response (high performance)
- [ ] Shadows
- [x] Hierarchical View Frustum Culling
- [x] Specialized Rendering technique 1 (Deferred Rendering, as in bloom?)
- [x] Specialized Rendering technique 2 (Textures that reflect sky box? aka Environment Mapping)

## Bonus Features
- [x] Level Creation Tool
- [x] Bloom
- [ ] Motion Blur
- [x] Particle System
- [x] Billboarding (in the particle system)
- [x] Fracture Mesh on collision
- [x] BONUS Procedurally Generated Level Based on Music 

## Other
- [x] Webpage
